export const PROJECTS = [
  {
    id: 'influence',
    index: '01',
    title: 'Influence Graph',
    company: 'Salesloft',
    year: '2024',
    hmw: 'How might we surface invisible stakeholder connections to help enterprise sellers navigate complex deals?',
    description: 'A 0→1 AI-powered relationship intelligence tool that helps enterprise sales teams visualize stakeholder networks and identify influence pathways within target accounts.',
    tags: ['AI/ML', 'Data Viz', 'B2B SaaS', '0→1'],
    route: '/work/influence-graph',
    passwordProtected: true,
    stats: [{ value: '0→1', label: 'Product launch' }, { value: 'Q1', label: 'Adoption target met' }],
    impactStatement: 'Helping enterprise AEs see the relationships that close deals',
  },
  {
    id: 'ai_email',
    index: '02',
    title: 'AI Email Assistant',
    company: 'Salesloft',
    year: '2023',
    hmw: 'How might we make AI writing feel like a collaborator, not a ghostwriter?',
    description: 'Generative AI email composition with built-in explainability — helping sales reps trust and edit AI suggestions while maintaining their authentic voice.',
    tags: ['Generative AI', 'Explainability', 'Productivity'],
    route: '/work/ai-email-assistant',
    passwordProtected: true,
    stats: [{ value: '2×', label: 'Adoption vs. prior AI' }, { value: '87%', label: 'Rep trust rating' }],
    impactStatement: 'Building trust in AI through transparency and explainability',
  },
  {
    id: 'github',
    index: '03',
    title: 'GitHub Pull Requests',
    company: 'Microsoft / GitHub',
    year: '2022',
    hmw: 'How might we improve the code review process for better collaboration among developers?',
    description: 'Developer UX research and systems design across core pull request workflows and CI/CD status visibility for 50M+ active users.',
    tags: ['Developer Tools', 'UX Research', 'Systems'],
    route: '/work/github',
    passwordProtected: false,
    stats: [{ value: '50M+', label: 'Active Users' }, { value: '1.5M+', label: 'Daily Pull Requests' }],
    impactStatement: 'Potentially streamlining workflow for millions of developers globally',
  },
  {
    id: 'sony',
    index: '04',
    title: 'Sony Audio',
    company: 'Sony',
    year: '2021',
    hmw: 'How might we make digital companion apps feel as considered as the hardware they complement?',
    description: "Consumer research and hardware-software interaction design for Sony's next-generation audio product line — bridging physical affordances with digital experiences.",
    tags: ['Consumer', 'Research', 'Hardware/Software'],
    route: '/work/sony',
    passwordProtected: false,
    stats: [{ value: 'Research', label: 'Consumer insights' }],
    impactStatement: 'Bridging physical affordances with digital companion experiences',
  },
]
